# ============================================================================
# application.yml - Configuración limpia y sin errores
# ============================================================================

server:
  port: 8082

spring:
  application:
    name: wizard-core
    
  datasource:
    url: jdbc:postgresql://localhost:5432/wizard_db
    username: wizard_user
    password: 4dminwzrd
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  jackson:
    serialization:
      fail-on-empty-beans: false
      
  task:
    scheduling:
      pool:
        size: 5
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 100

# ============================================================================
# Configuración de Swagger/OpenAPI
# ============================================================================
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    enabled: true
    doc-expansion: none
    show-extensions: true
    syntax-highlight:
      theme: monokai
  api-docs:
    path: /api-docs

# ============================================================================
# Configuración de Logging
# ============================================================================
logging:
  level:
    com.wizard.core.modules.pacs: DEBUG
    com.wizard.core.modules.pacs.integration: DEBUG
    com.wizard.core.modules.pacs.service: INFO
    org.springframework.retry: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.scheduling: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/wizard-pacs.log
    max-size: 100MB
    max-history: 30

# ============================================================================
# Información de la aplicación
# ============================================================================
info:
  title: Wizard API
  description: API de gestión de organizaciones y sedes con módulo PACS integrado
  version: 1.0.0

# ============================================================================
# Configuración de Spring Actuator
# ============================================================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    wizard-pacs-engine:
      enabled: true
  metrics:
    tags:
      application: wizard-pacs
      environment: development
  prometheus:
    metrics:
      export:
        enabled: true

# ============================================================================
# Configuración de Wizard PACS
# ============================================================================
wizard:
  pacs:
    # Motor PACS (DCM4CHEE en Docker)
    engine:
      url: http://localhost:8083  # DCM4CHEE corriendo en Docker puerto 8080
      username: admin
      password: admin
      defaultAeTitle: WIZARD_PACS
      timeout: 30000
      retryAttempts: 3
      retryDelay: 2000
    
    # Visor web
    viewer:
      baseUrl: http://localhost:8080/wizard-viewer
      sessionTimeoutMinutes: 60
      maxConcurrentSessions: 100
    
    # Configuraciones DICOM
    dicom:
      maxConnections: 50
      connectionTimeout: 30000
      responseTimeout: 60000
      idleTimeout: 30000
      # SOP Classes soportadas
      supportedSopClasses:
        - "1.2.840.10008.5.1.4.1.1.2"      # CT Image Storage
        - "1.2.840.10008.5.1.4.1.1.1.2"    # Enhanced CT Image Storage
        - "1.2.840.10008.5.1.4.1.1.4"      # MR Image Storage
        - "1.2.840.10008.5.1.4.1.1.1"      # Computed Radiography Image Storage
        - "1.2.840.10008.5.1.4.1.1.12.1"   # X-Ray Angiographic Image Storage
        - "1.2.840.10008.5.1.4.1.1.7"      # Secondary Capture Image Storage
        - "1.2.840.10008.5.1.4.1.1.104.1"  # Encapsulated PDF Storage

      
    integration:
      auto-create-ae-titles: true
      sync-studies: true
      enable-echo-monitoring: true
      branding: "Wizard PACS Engine"
      batch-echo-interval: 300
      enable-audit-log: true